apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-domains-operator
  namespace: custom-domains-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: custom-domains-operator
  template:
    metadata:
      labels:
        name: custom-domains-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      serviceAccountName: custom-domains-operator
      containers:
        - name: custom-domains-operator
          image: quay.io/tsuedbroecker/custom-domains-operator:v1
          command:
          - custom-domains-operator
          args:
            - "--zap-level=debug"
            - "--zap-encoder=console"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "custom-domains-operator"
