apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: public
  namespace: openshift-ingress-operator
spec:
  replicas: 2
  domain: "apps.suedbroecker.org"
  endpointPublishingStrategy:
    loadBalancer:
      scope: External
    type: LoadBalancerService
